Repository Evan-Kork/temabit-lections-2019, pull requests merged in 2019-10, with the labels that each got.

#6 Feature/10 yevhen derevyanko/dz 1
  10-yevhen-derevyanko/dz-1/README.md
Labels: documentation

#13 Feature/12 zheka klimovych/dz 1
  12-zheka-klimovych/dz-1/README.md
Labels: documentation

#23 Feature/13 vitalii hushpet/dz 1
  13-vitalii-hushpet/dz-1/README.md
Labels: documentation

#3 added file in my first hometask
  1-oleh-tryhuba/dz-1/README.md
Labels: documentation

#22 Feature/14 viacheslav semeniuk/dz 1
  14-viacheslav-semeniuk/dz-1/README.md
Labels: dz2, ready

#18 Feature/7-mikhail-biloshkyrskiyy/dz1
  7-mikhail-biloshkyrskiyy/dz-1/README.md
Labels: dz2

#1 Feature/6 vasyl savitskyy/dz 1
  6-vasyl-savitskyy/dz-1/README.md
Labels: dz2

#8 Feature/5 vladyslav hudyma/dz 1
  5-vladyslav-hudyma/dz1/README.md
Labels: dz2

#7 Feature/15 denys honcharuk/dz 1
  15-denys-honcharuk/dz-1/README.md
Labels: dz2

#11 Feature/17 yuliia mysko/dz 1
  17-yuliia-mysko/dz-1/README.md
Labels: dz2

#14 Feature/18 kate ivinska/dz 1
  18-kate-ivinska/dz-1/README.md
Labels: dz-2, ready

#25 Feature/21-yaroslav-kryvush/dz-1
  21-yaroslav-kryvush/dz-1/README.md
Labels: dz-2, ready

#27 feature/25-zenchenko-oleksandr/dz-1
  25-zenchenko-oleksandr/dz-1/README.md
Labels: dz-2, ready

#36 Feature/19 vitaliy zayets/dz 1
  19-vitaliy-zayets/dz-1/README.md
Labels: dz-2, ready

#33 Feature/4 kostyantyn kucher/dz 1
  4-kostyantyn-kucher/dz-1/README.md
Labels: dz-2, ready

#28 Feature/33 yaroslav babiuk/dz 1
  33-yaroslav-babiuk/dz-1/README.md
Labels: dz-2, ready

#20 Feature/34 mykhailo vaskivnyuk/dz 1
  34-mykhailo-vaskivnyuk/dz-1/README.md
Labels: dz-2, ready

#34 Feature/20 kostileckiy roman/dz1
  20-kostileckiy-roman/dz-1/README.md
Labels: dz-2, ready

#31 Feature/35 evgeniy kovrukov/dz 1
  35-evgeniy-kovrukov/dz-1/README.md
Labels: dz-2, merge

#39 Feature/9 ruslan kahalniak/dz 1
  9-ruslan-kahalniak/dz-1/README.md
Labels: dz-2

#41 feature/8-mariia-trusiuk/dz-1
  8-mariia-trusiuk/dz-1/README.md
Labels: dz-2, merge

#40 feature/26-sergey-urdinets/dz-1
  26-urdinets-sergey/dz-1/README.md
Labels: dz-2, merge

#21 Feature/27-dmitriy-dankov/dz-1
  27-dmitriy-dankov/dz-1/README.md
Labels: dz-2

#49 feature/14-viacheslav-semeniuk/dz-4
  14-viacheslav-semeniuk/dz-4/css/index.css
  14-viacheslav-semeniuk/dz-4/index.html
Labels: dz-4, merge

#48 Feature/12 zheka klimovych/dz 4
  12-zheka-klimovych/dz-4/css/index.css
  12-zheka-klimovych/dz-4/index.html
Labels: dz-4, merge

#51 feature/13-vitalii-hushpet/dz-4
  13-vitalii-hushpet/dz-4/css/style.css
  13-vitalii-hushpet/dz-4/index.html
Labels: dz-4, merge

#57 feature/08-mariia-trusiuk/dz-4
  08-mariia-trusiuk/dz-1/README.md
  08-mariia-trusiuk/dz-4/index.html
  08-mariia-trusiuk/dz-4/style.css
Labels: dz-4, merge

#50 feature/3-alexander-mironenko/dz-4
  3-alexander-mironenko/dz-4/css/index.css
  3-alexander-mironenko/dz-4/index.html
Labels: dz-4, merge

#59 feature/1-oleh-tryhuba/dz-4
  01-oleh-tryhuba/dz-1/README.md
  01-oleh-tryhuba/dz-4/css/style.css
  01-oleh-tryhuba/dz-4/index.html
Labels: dz-4, merge

#60 feature/17-yuliia-mysko/dz-4
  17-yuliia-mysko/dz-4/css/index.css
  17-yuliia-mysko/dz-4/index.html
Labels: dz-4, merge

#55 Feature/10 yevhen derevyanko/dz 4
  10-yevhen-derevyanko/dz-4/css/style.css
  10-yevhen-derevyanko/dz-4/image/caniuse-bg.png
  10-yevhen-derevyanko/dz-4/image/prefix.svg
  10-yevhen-derevyanko/dz-4/index.html
  10-yevhen-derevyanko/dz-4/prepros-6.config
  10-yevhen-derevyanko/dz-4/scss/style.scss
Labels: dz-4, merge

#66 Update index.css
  06-vasyl-savitskyy/dz-4/css/index.css
Labels: dz-4, merge

#46 feature/7-mikhail-biloshkyrskiyy/dz4
  7-mikhail-biloshkyrskiyy/dz-4/assets/css/main.css
  7-mikhail-biloshkyrskiyy/dz-4/assets/css/main.css.map
  7-mikhail-biloshkyrskiyy/dz-4/assets/css/main.scss
  7-mikhail-biloshkyrskiyy/dz-4/assets/data/browser.json
  7-mikhail-biloshkyrskiyy/dz-4/assets/script/script.js
  7-mikhail-biloshkyrskiyy/dz-4/index.html
Labels: dz-4, ready

#65 feature/15-denys-honcharuk/dz-4
  15-denys-honcharuk/dz-4/css/index.css
  15-denys-honcharuk/dz-4/index.html
Labels: dz-4, merge

#54 Feature/2 oleg ferenets/dz 4
  2-oleg-ferenets/dz-4/css/index.css
  2-oleg-ferenets/dz-4/index.html
Labels: dz-4, merge

#30 feature/32-julia-musienko/dz-1
  32-julia-musienko/dz-1/README.md
Labels: dz-2, merge

#62 Feature/11 evgenii khvorostyuk/dz 4
  11-evgenii-khvorostyuk/.gitignore
  11-evgenii-khvorostyuk/dz-4/caniuse.html
  11-evgenii-khvorostyuk/dz-4/css/index.css
  11-evgenii-khvorostyuk/dz-4/img/caniuse-bg.png
  11-evgenii-khvorostyuk/dz-4/img/favicon-128.png
  11-evgenii-khvorostyuk/dz-4/scss/_vars.scss
  11-evgenii-khvorostyuk/dz-4/scss/index.scss
  11-evgenii-khvorostyuk/lection-4/css/index.css
  11-evgenii-khvorostyuk/lection-4/index.html
Labels: dz-4, merge

#64 feature/5-vladyslav-hudyma/dz-4
  dz-4/css/index.css
  dz-4/index.html
Labels: dz-4

#43 feature/16-vladimir-borovskyi/dz-1
  16-vladimir-borovskiy/dz-01/README.md
  16-vladimir-borovskiy/dz-04/css/index.css
  16-vladimir-borovskiy/dz-04/index.html
Labels: dz-2

#72 Feature/20 kostyleckiy roman/dz 4
  20-kostileckiy-roman/dz-4/README.md
  20-kostileckiy-roman/dz-4/css/main.css
  20-kostileckiy-roman/dz-4/index.html
Labels: dz-4, merge

#61 feature/22-mariia-asaulenko/dz-4
  22-mariia-asaulenko/dz-4/css/style.css
  22-mariia-asaulenko/dz-4/images/img_358934.png
  22-mariia-asaulenko/dz-4/index.html
Labels: dz-4, merge

#88 feature/01-oleh-tryhuba/dz-5
  01-oleh-tryhuba/dz-5/css/style.css
  01-oleh-tryhuba/dz-5/index.html
Labels: dz-5, merge

#68 feature/25-zenchenko-oleksandr/dz-4
  25-zenchenko-oleksandr/dz-4/index.html
  25-zenchenko-oleksandr/dz-4/style.css
Labels: dz-4, merge

#96 feature/15-denys-honcharuk/dz-5
  15-denys-honcharuk/dz-5/css/style.css
  15-denys-honcharuk/dz-5/fonts/PFDinTextCompPro-Regular.woff
  15-denys-honcharuk/dz-5/index.html
Labels: dz-5, merge

#85 Feature/11 evgenii khvorostyuk/dz 5
  11-evgenii-khvorostyuk/dz-5/css/style.css
  11-evgenii-khvorostyuk/dz-5/index.html
  11-evgenii-khvorostyuk/dz-5/scss/style.scss
Labels: dz-5, merge

#81 feature/14-viacheslav-semeniuk/dz-5
  14-viacheslav-semeniuk/dz-5/css/index.css
  14-viacheslav-semeniuk/dz-5/index.html
Labels: dz-5, merge

#103 featute/10-yevhen-derevyanko/dz-5
  10-yevhen-derevyanko/dz-5/css/style.css
  10-yevhen-derevyanko/dz-5/image/google-logo.svg
  10-yevhen-derevyanko/dz-5/index.html
  10-yevhen-derevyanko/dz-5/prepros-6.config
  10-yevhen-derevyanko/dz-5/scss/style.scss
Labels: dz-5, merge

#91 feature/12-zheka-klimovych/dz-5
  12-zheka-klimovych/dz-5/css/style.css
  12-zheka-klimovych/dz-5/index.html
Labels: dz-5, merge

#90 feature/02-oleg-ferenets/dz-5
  02-oleg-ferenets/dz-1/README.md
  02-oleg-ferenets/dz-4/css/index.css
  02-oleg-ferenets/dz-4/index.html
  02-oleg-ferenets/dz-5/css/index.css
  02-oleg-ferenets/dz-5/index.html
Labels: dz-5, merge

#105 feature/20-kostyleckiy-roman/dz-5
  20-kostileckiy-roman/dz-5/css/main.css
  20-kostileckiy-roman/dz-5/img/googlelogo.png
  20-kostileckiy-roman/dz-5/index.html
Labels: dz-5, merge

#78 Hometask №4 with changed classes
  04-kostyantyn-kucher/dz-4/index.html
  04-kostyantyn-kucher/dz-4/style.css
Labels: dz-4, merge

#106 feature/25-zenchenko-oleksandr/dz-5
  25-zenchenko-oleksandr/dz-5/index.html
  25-zenchenko-oleksandr/dz-5/style.css
Labels: dz-5, merge

#52 feature/21-yaroslav-kryvush/dz-4
  21-yaroslav-kryvush/dz-4/css/style.css
  21-yaroslav-kryvush/dz-4/index.html
Labels: dz-4, merge

#93 Feature/06 vasyl savitskyy/dz 5
  06-vasyl-savitskyy/dz-5/css/index.css
  06-vasyl-savitskyy/dz-5/img/googlelogo_color_92x30dp.png
  06-vasyl-savitskyy/dz-5/index.html
Labels: dz-5, merge

#111 feature/03-alexander-mironenko/dz-5
  03-alexander-mironenko/dz-1/README.md
  03-alexander-mironenko/dz-4/css/index.css
  03-alexander-mironenko/dz-4/index.html
  03-alexander-mironenko/dz-5/index.css
  03-alexander-mironenko/dz-5/index.html
Labels: dz-5, merge

#80 feature/13-vitalii-hushpet/dz-5
  13-vitalii-hushpet/dz-5/index.html
  13-vitalii-hushpet/dz-5/style.css
Labels: dz-5, merge

#99 feature/21-yaroslav-kryvush/dz-5
  21-yaroslav-kryvush/dz-5/css/style.css
  21-yaroslav-kryvush/dz-5/index.html
Labels: dz-5, merge

#79 feature/7-mikhail-biloshkyrskiyy/dz5
  07-mikhail-biloshkyrskiyy/dz-5/.gitignore
  07-mikhail-biloshkyrskiyy/dz-5/assets/style/main.css
  07-mikhail-biloshkyrskiyy/dz-5/assets/style/profile.css
  07-mikhail-biloshkyrskiyy/dz-5/index.html
  07-mikhail-biloshkyrskiyy/dz-5/profile.html
Labels: dz-5, merge
