Repository Evan-Kork/temabit-lections-2019, pull requests merged in 2019-12, with the labels that each got.

#117 Feature/09 ruslan kahalniak/dz 4
  09-ruslan-kahalniak/dz-4/index.html
  09-ruslan-kahalniak/dz-4/style.css
Labels: dz-4, merge

#208 feature/07-mikhail-biloshkyrskiyy/dz10
  07-mikhail-biloshkyrskiyy/dz-10/.gitignore
  07-mikhail-biloshkyrskiyy/dz-10/assets/script/main.js
  07-mikhail-biloshkyrskiyy/dz-10/index.html
  07-mikhail-biloshkyrskiyy/dz-10/package-lock.json
  07-mikhail-biloshkyrskiyy/dz-10/package.json
Labels: dz-10, ready

#211 feature/01-oleh-tryhuba/dz-10
  01-oleh-tryhuba/dz-10/index.js
Labels: dz-10

#221 feature/24-olga-redko/dz-10
  24-olga-redko/dz-10/README.md
  24-olga-redko/dz-10/index.html
  24-olga-redko/dz-10/script.js
Labels: dz-10

#226 feature/02-oleg-ferenets/dz-10
  02-oleg-ferenets/dz-10/index.html
  02-oleg-ferenets/dz-10/js1.js
Labels: dz-10, ready

#218 feature/03-alexander-mironenko/dz-10
  03-alexander-mironenko/dz-10/index.html
  03-alexander-mironenko/dz-10/js.js
Labels: dz-10, ready

#220 feature/35-evgeniy-kovrukov/dz-10
  35-evgeniy-kovrukov/dz-10/index.js
Labels: dz-10, ready

#214 Feature/34 mykhailo vaskivnyuk/dz 10
  34-mykhailo-vaskivnyuk/dz-10/index.html
  34-mykhailo-vaskivnyuk/dz-10/script.js
  34-mykhailo-vaskivnyuk/dz-10/style.css
Labels: dz-10, ready

#213 feature/20-kostyleckiy-roman/dz-10
  20-kostileckiy-roman/dz-10/1task.js
Labels: dz-10, ready

#229 feature/22-mariia-asaulenko/dz-10
  22-mariia-asaulenko/index.html
  22-mariia-asaulenko/index.js
Labels: dz-10

#223 Feature/10-yevhen-derevyanko/dz-10
  10-yevhen-derevyanko/dz-10/css/style.css
  10-yevhen-derevyanko/dz-10/index.html
  10-yevhen-derevyanko/dz-10/js/script.js
Labels: dz-10

#232 feature/18-kate-ivinska/dz-10
  18-kate-ivinska/dz-10/index.html
  18-kate-ivinska/dz-10/index.js
Labels: dz-10

#238 11 evgenii khvorostyuk/dz 10
  11-evgenii-khvorostyuk/dz-10/index.js
Labels: dz-10

#239 feature/12-zheka-klimovych/dz-10
  12-zheka-klimovych/dz-10/index.html
  12-zheka-klimovych/dz-10/index.js
Labels: dz-10
