Repository Evan-Kork/temabit-lections-2019, pull requests merged in 2019-11, with the labels that each got.

#83 Feature/22-mariia-asaulenko/dz-5
  22-mariia-asaulenko/dz-5/css/style.css
  22-mariia-asaulenko/dz-5/index.html
Labels: dz-5, merge

#67 feature/26-sergey-urdinets/dz-4
  26-sergey-urdinets/dz-1/README.md
  26-sergey-urdinets/dz-4/css/index.css
  26-sergey-urdinets/dz-4/index.html
Labels: dz-4, merge

#118 feature/01-oleh-tryhuba/dz-6
  01-oleh-tryhuba/.gitignore
  01-oleh-tryhuba/dz-6/index.html
  01-oleh-tryhuba/dz-6/style.css
Labels: dz-6, merge

#109 Feature/24 olga redko/dz 1
  24-olga-redko/dz-1/README.md
Labels: dz-1, merge

#112 feature/24-olga-redko/dz-4
  24-olga-redko/dz-4/css/style.css
  24-olga-redko/dz-4/index.html
Labels: dz-4, merge

#123 feature/22-mariia-asaulenko/dz-6
  22-mariia-asaulenko/dz-6/css/style.css
  22-mariia-asaulenko/dz-6/img/bucks.jpg
  22-mariia-asaulenko/dz-6/img/header-project-2.jpg
  22-mariia-asaulenko/dz-6/index.html
Labels: dz-6, merge

#69 Feature/34 mykhailo vaskivnyuk/dz 4
  34-mykhailo-vaskivnyuk/dz-4/css/index.css
  34-mykhailo-vaskivnyuk/dz-4/index.html
Labels: dz-4, merge

#133 feature/06-vasyl-savitskyy/dz-7
  06-vasyl-savitskyy/dz-7/css/index.css
  06-vasyl-savitskyy/dz-7/index.html
Labels: dz-7, merge

#73 Feature/27 dmitriy dankov/dz 4
  27-dmitriy-dankov/dz-4/css/index.css
  27-dmitriy-dankov/dz-4/index.html
Labels: dz-4, merge

#131 feature/7-mikhail-biloshkyrskiyy/dz6
  07-mikhail-biloshkyrskiyy/dz-6/.gitignore
  07-mikhail-biloshkyrskiyy/dz-6/assets/images/house_1.png
  07-mikhail-biloshkyrskiyy/dz-6/assets/images/house_2.png
  07-mikhail-biloshkyrskiyy/dz-6/assets/images/house_3.png
  07-mikhail-biloshkyrskiyy/dz-6/assets/images/house_4.png
  07-mikhail-biloshkyrskiyy/dz-6/assets/images/logo.png
  07-mikhail-biloshkyrskiyy/dz-6/assets/images/main.png
  07-mikhail-biloshkyrskiyy/dz-6/assets/style/main.css
  07-mikhail-biloshkyrskiyy/dz-6/index.html
Labels: dz-6, merge

#58 feature/35-evgeniy-kovrukov/dz-4
  35-evgeniy-kovrukov/dz-4/index.html
  35-evgeniy-kovrukov/dz-4/syyle.css
Labels: dz-4, merge

#139 feature/24-olga-redko/dz-5
  24-olga-redko/dz-5/index.html
  24-olga-redko/dz-5/main.css
Labels: dz-5, merge

#128 feature/24-olga-redko/dz-6
  24-olga-redko/dz-6/img/house.jpg
  24-olga-redko/dz-6/index.html
  24-olga-redko/dz-6/main.css
Labels: dz-6, merge

#115 Feature/05 vladyslav hudyma/dz 5
  05-vladyslav-hudyma/dz-5/css/index.css
  05-vladyslav-hudyma/dz-5/index.html
Labels: dz-5, merge

#53 feature/18-kate-ivinska/dz-4
  18-kate-ivinska/dz-4/css/index.css
  18-kate-ivinska/dz-4/index.html
Labels: dz-4, merge

#137 feature/01-oleh-tryhuba/dz-7
  01-oleh-tryhuba/.gitignore
  01-oleh-tryhuba/dz-7/index.html
  01-oleh-tryhuba/dz-7/style.css
Labels: dz-7, merge

#116 feature/03-alexander-mironenko/dz-6
  03-alexander-mironenko/dz-6/flex.css
  03-alexander-mironenko/dz-6/img/hed.jpg
  03-alexander-mironenko/dz-6/img/house01.jpg
  03-alexander-mironenko/dz-6/img/house02.jpg
  03-alexander-mironenko/dz-6/img/house03.jpg
  03-alexander-mironenko/dz-6/img/house04.jpg
  03-alexander-mironenko/dz-6/index.html
  03-alexander-mironenko/dz-6/media.css
Labels: dz-6, merge

#121 feature/02-oleg-ferenets/dz-6
  02-oleg-ferenets/dz-6/css/index.css
  02-oleg-ferenets/dz-6/img/H-173-1P.jpg
  02-oleg-ferenets/dz-6/img/d-152-1d.jpg
  02-oleg-ferenets/dz-6/img/logo.gif
  02-oleg-ferenets/dz-6/img/r-280-1d.jpg
  02-oleg-ferenets/dz-6/img/shapka.jpg
  02-oleg-ferenets/dz-6/img/v-208-1p.jpg
  02-oleg-ferenets/dz-6/index.html
Labels: dz-6, merge

#122 dz-6 v0.1
  06-vasyl-savitskyy/dz-6/css/index.css
  06-vasyl-savitskyy/dz-6/img/01.jpg
  06-vasyl-savitskyy/dz-6/img/02.jpg
  06-vasyl-savitskyy/dz-6/img/03.jpg
  06-vasyl-savitskyy/dz-6/img/04.jpg
  06-vasyl-savitskyy/dz-6/img/catalog.png
  06-vasyl-savitskyy/dz-6/img/dz-6-header.jpg
  06-vasyl-savitskyy/dz-6/index.html
Labels: dz-6, merge

#100 feature/16 vladimir borovskyi/dz-04
  16-vladimir-borovskiy/dz-04/homework.css
  16-vladimir-borovskiy/dz-04/homework.html
Labels: dz-4, merge

#97 feature/16 vladimir borovskyi/dz-01
  16-vladimir-borovskiy/dz-01/README.md
Labels: dz-2, merge

#126 feature/12-zheka-klimovych/dz-6
  12-zheka-klimovych/dz-6/css/style.css
  12-zheka-klimovych/dz-6/img/header.jpg
  12-zheka-klimovych/dz-6/index.html
Labels: dz-6, merge

#145 feature/7-mikhail-biloshkyrskiyy/dz7
  07-mikhail-biloshkyrskiyy/dz-7/.gitignore
  07-mikhail-biloshkyrskiyy/dz-7/assets/style/main.css
  07-mikhail-biloshkyrskiyy/dz-7/index.html
Labels: dz-7, merge

#135 Feature/10-yevhen-derevyanko/dz-7
  10-yevhen-derevyanko/dz-7/css/style.css
  10-yevhen-derevyanko/dz-7/image/head-bg.jpg
  10-yevhen-derevyanko/dz-7/image/logo.png
  10-yevhen-derevyanko/dz-7/image/project-1.jpg
  10-yevhen-derevyanko/dz-7/image/project-2.jpg
  10-yevhen-derevyanko/dz-7/image/project-3.jpg
  10-yevhen-derevyanko/dz-7/image/project-4.jpg
  10-yevhen-derevyanko/dz-7/index.html
  10-yevhen-derevyanko/dz-7/prepros-6.config
  10-yevhen-derevyanko/dz-7/scss/style.scss
Labels: dz-7, merge

#134 Feature/10 yevhen derevyanko/dz 6
  10-yevhen-derevyanko/dz-6/css/style.css
  10-yevhen-derevyanko/dz-6/image/head-bg.jpg
  10-yevhen-derevyanko/dz-6/image/logo.png
  10-yevhen-derevyanko/dz-6/image/project-1.jpg
  10-yevhen-derevyanko/dz-6/image/project-2.jpg
  10-yevhen-derevyanko/dz-6/image/project-3.jpg
  10-yevhen-derevyanko/dz-6/image/project-4.jpg
  10-yevhen-derevyanko/dz-6/index.html
  10-yevhen-derevyanko/dz-6/prepros-6.config
  10-yevhen-derevyanko/dz-6/scss/style.scss
Labels: dz-6, merge

#163 feature/12-zheka-klimovych/dz-7
  12-zheka-klimovych/dz-7/css/style.css
  12-zheka-klimovych/dz-7/index.html
Labels: dz-7, merge

#173 feature/16-vladimir-borovskyi/dz-05
  16-vladimir-borovskiy/dz-05/index.html
  16-vladimir-borovskiy/dz-05/style.css
  16-vladimir-borovskiy/scss.html
  16-vladimir-borovskiy/scss/maim.css
  16-vladimir-borovskiy/scss/maim.css.map
  16-vladimir-borovskiy/scss/maim.scss
Labels: dz-5, merge

#171 feature/17-yuliia-mysko/dz-6
  17-yuliia-mysko/dz-6/images/banner.jpg
  17-yuliia-mysko/dz-6/images/icon.png
  17-yuliia-mysko/dz-6/images/project-152.jpg
  17-yuliia-mysko/dz-6/images/project-173.jpg
  17-yuliia-mysko/dz-6/images/project-208.jpg
  17-yuliia-mysko/dz-6/images/project-280.jpg
  17-yuliia-mysko/dz-6/index.html
  17-yuliia-mysko/dz-6/style.css
Labels: dz-6, merge

#84 Feature/04 kostyantyn kucher/dz 5
  04-kostyantyn-kucher/dz-5/index.html
  04-kostyantyn-kucher/dz-5/style.css
Labels: dz-5, merge

#125 feature/24-olga-redko/dz-7
  24-olga-redko/dz-7/css/main.css
  24-olga-redko/dz-7/img/icon_close.png
  24-olga-redko/dz-7/img/icon_menu.png
  24-olga-redko/dz-7/index.html
Labels: dz-7, merge

#113 feature/35-evgeniy-kovrukov/dz-5
  35-evgeniy-kovrukov/dz-5/images/googlelogo_color_272x92dp.png
  35-evgeniy-kovrukov/dz-5/index.html
  35-evgeniy-kovrukov/dz-5/style.css
Labels: dz-5, merge

#74 feature/33 yaroslav babiuk/dz-4
  33-yaroslav-babiuk/dz-4/css/index.css
  33-yaroslav-babiuk/dz-4/index.html
Labels: dz-4, merge

#104 Feature/34 mykhailo vaskivnyuk/dz 5
  34-mykhailo-vaskivnyuk/dz-5/css/index.css
  34-mykhailo-vaskivnyuk/dz-5/index.html
Labels: dz-5, merge

#98 featute/18-kate-ivinska/dz-5
  18-kate-ivinska/dz-5/index.css
  18-kate-ivinska/dz-5/index.html
Labels: dz-5, merge

#124 feature/14-viacheslav-semeniuk/dz-6
  14-viacheslav-semeniuk/dz-6/assets/header.jpg
  14-viacheslav-semeniuk/dz-6/assets/house.jpg
  14-viacheslav-semeniuk/dz-6/css/index.css
  14-viacheslav-semeniuk/dz-6/index.html
Labels: dz-6, merge

#127 Feature/04 kostyantyn kucher/dz 6
  04-kostyantyn-kucher/.geetkeep
  04-kostyantyn-kucher/dz-6/images/header.jpg
  04-kostyantyn-kucher/dz-6/images/logo.jpeg
  04-kostyantyn-kucher/dz-6/images/tooth.png
  04-kostyantyn-kucher/dz-6/index.html
  04-kostyantyn-kucher/dz-6/style.css
Labels: dz-6, merge

#114 feature/08-mariia-trusiuk/dz-5
  08-mariia-trusiuk/dz-5/index.html
  08-mariia-trusiuk/dz-5/style.css
Labels: dz-5, merge

#175 feature/16-vladimir-borovskyi/dz-06
  16-vladimir-borovskiy/dz-06/img/header.jpg
  16-vladimir-borovskiy/dz-06/img/item-1.jpg
  16-vladimir-borovskiy/dz-06/img/item-2.jpg
  16-vladimir-borovskiy/dz-06/img/item-3.jpg
  16-vladimir-borovskiy/dz-06/img/item-4.jpg
  16-vladimir-borovskiy/dz-06/img/logo.jpg
  16-vladimir-borovskiy/dz-06/index.html
  16-vladimir-borovskiy/dz-06/style.css
Labels: dz-6, merge

#219 feature/06-vasyl-savitskyy/dz-10
  06-vasyl-savitskyy/dz-10/index.html
  06-vasyl-savitskyy/dz-10/js/main.js
  06-vasyl-savitskyy/dz-10/js/readme.md
Labels: dz-10, ready
